# Generated by Django 4.2.3 on 2023-08-22 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_category_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='title',
            new_name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
