# Generated by Django 4.2.3 on 2023-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageLink',
            field=models.TextField(),
        ),
    ]
