# Generated by Django 4.2.3 on 2023-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageLink',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
